const express=require("express")
const route=express.Router()
const AdminRender=require("../services/AdminRender")
const AdminController=require("../controller/AdminController")
const CouponController=require("../controller/couponController")
const productController=require("../controller/productController")
const Adminauthentication=require('../Middlewares/middleware')
const multer=require("multer")

route.get('/api/UserManagement',AdminController.UserManage)

route.get('/userManage',Adminauthentication.isAdmin,AdminRender.userManage)
route.get('/adminsdash',Adminauthentication.isAdmin, AdminRender.Dashboard)
route.get('/adminlogin',Adminauthentication.NotAdmin, AdminRender.Adminlogin)
route.post('/api/adminlogin',AdminController.Adminauth)
route.get('/api/unlisted',AdminController.unlisted)
route.post('/api/category',AdminController.categoryManage)
route.get('/api/categoryFind',AdminController.CategoryFind)
route.get('/api/categoryUnlist',AdminController.categoryUnlist)
route.get('/api/listed',AdminController.listed)
route.get('/adminCategory',Adminauthentication.isAdmin,AdminRender.adminCategory)
route.get('/unlistedCategory',Adminauthentication.isAdmin,AdminRender.unlistedCategory) 
route.get('/editCategory',Adminauthentication.isAdmin,AdminRender.editCategory)
route.get('/api/CategoryEdit',AdminController.CategoryEdit)
route.post('/api/updatecategory',AdminController.updateCategory)
route.get('/addProduct',Adminauthentication.isAdmin,AdminRender.addProduct)
route.get('/productlist',Adminauthentication.isAdmin,AdminRender.productList)
route.get('/productUnlist',Adminauthentication.isAdmin,AdminRender.productUnlist)
route.post('/api/newProduct',productController.uploads.array('Images', 4),productController.newProduct)

route.get('/api/productlist',productController.listedProducts)
route.get('/api/unlistedProducts',productController.unlistedProducts)
route.get('/api/addProductlist',productController.addProductlist)
route.get('/api/deleteProductlist',productController.deleteProductlist)
route.get('/api/docFind',productController.productEdit)
route.post('/api/updateProdcut',productController.uploads.array('newImages', 4),productController.updateProducts )
route.get('/delete-image',productController.deleteImage)
route.get('/orderManage',AdminRender.orderManage)
route.get('/api/OrdersManage',AdminController.orderAdmin)
route.post('/api/saveStatus',AdminController.saveStatus)
route.get('/api/totalOrders',AdminController.totalOrders)
route.get('/gotProductedit',AdminRender.gotProductedit)
route.get('/itemDetails',AdminRender.itemDetails)
route.get('/api/singleOrderDetail',AdminController.singleOrderDetail)
route.post('/api/getDetailsChart',AdminController.getDetailsChart)
route.get('/salesReport',AdminController.salesReport)
route.get('/api/toProducts',AdminController.ftProducts)
route.get('/addCoupon',AdminRender.addCoupon)
route.post('/api/addCoup',CouponController.createCoupon)
route.get('/api/deleteCoupon',CouponController.deleteCoupon)
route.get('/CouponEdit',AdminRender.couponEdit)
route.post('/api/editCoup',CouponController.editCoupon)


module.exports=route